-- Update apps table to add new columns according to ERD
ALTER TABLE apps ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE apps ADD COLUMN IF NOT EXISTS is_available BOOLEAN DEFAULT TRUE;
ALTER TABLE apps ADD COLUMN IF NOT EXISTS max_group_members INTEGER DEFAULT 5;
ALTER TABLE apps ADD COLUMN IF NOT EXISTS total_price DECIMAL(15,2) DEFAULT 0.00;
ALTER TABLE apps ADD COLUMN IF NOT EXISTS admin_fee_percentage DECIMAL(5,2) DEFAULT 10.00;
