-- Update groups table to add new columns according to ERD
ALTER TABLE groups ADD COLUMN IF NOT EXISTS app_id VARCHAR(50) REFERENCES apps(id);
ALTER TABLE groups ADD COLUMN IF NOT EXISTS current_members INTEGER DEFAULT 0;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS price_per_member DECIMAL(15,2) DEFAULT 0.00;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS admin_fee DECIMAL(15,2) DEFAULT 0.00;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS total_price DECIMAL(15,2) DEFAULT 0.00;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'open';
ALTER TABLE groups ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP;
