# SALOME Platform Configuration
# Development Environment

database:
  host: 100.87.18.78
  port: 5434
  user: myuser
  password: mypassword
  name: salome
  ssl_mode: disable

jwt:
  secret: salome-super-secret-jwt-key-2024-change-in-production
  expiry: 24h

server:
  port: 8080
  host: localhost
  cors_origins:
    - http://localhost:3000
    - http://localhost:3001
    - https://salome-api.cloudfren.id
    - https://salome.cloudfren.id
    - https://cloudfren-core.cloudfren.id
    - http://localhost:8080
    - https://api.cloudfren.id

email:
  smtp_host: smtp.gmail.com
  smtp_port: 587
  username: your-email@gmail.com
  password: your-app-password
  from_name: SALOME Platform
  from_email: noreply@salome.com
  mailersend:
    api_key: mlsn.68c371b2819cdd118002ec60a6211a8570ccf30f14e303fdb3d6126372b48b7e
    from_email: noreply@salome.cloudfren.id
    from_name: SALOME Platform
    enabled: false  # Disabled - using Resend instead
  resend:
    api_key: re_f9QGSeaa_NVc51ck3MTEqS832WwnrEwxv
    from_email: noreply@salome2.cloudfren.id
    from_name: SALOME Platform
    enabled: true  # Using Resend as primary email provider

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

security:
  bcrypt_cost: 12
  session_secret: salome-session-secret-2024

features:
  enable_otp: true
  enable_email_verification: true
  enable_payment_gateway: true
  enable_notifications: true

midtrans:
  server_key: "SB-Mid-server-i1dcC7yEZ88t9ojPby0wej3n"
  client_key: "SB-Mid-client-F4GiAgWMbYRqrHzr"
  base_url: "https://api.sandbox.midtrans.com"
  is_production: false
  payment_link:
    check_url: "https://api.sandbox.midtrans.com/v1/payment-links"
    web_url: "https://app.sandbox.midtrans.com/payment-links"
    timeout: 30s
    retry_attempts: 3
    retry_delay: 5s
  webhook:
    enabled: true
    secret_key: "salome-midtrans-webhook-secret-2024"
    timeout: 10s

# #STAGING
# midtrans:
#   midtrans_server_key: SB-Mid-server-i1dcC7yEZ88t9ojPby0wej3n
#   midtrans_client_key: SB-Mid-client-F4GiAgWMbYRqrHzr
#   midtrans_base_url: https://api.sandbox.midtrans.com
#   midtrans_default_version: v2
#   midtrans_api_version: v1