# SALOME Platform Configuration
# Development Environment

database:
  host: 100.87.18.78
  port: 5434
  user: myuser
  password: mypassword
  name: salome
  ssl_mode: disable

jwt:
  secret: salome-super-secret-jwt-key-2024-change-in-production
  expiry: 24h

server:
  port: 8080
  host: localhost
  cors_origins:
    - http://localhost:3000
    - http://localhost:3001
    - https://salome-api.cloudfren.id

email:
  smtp_host: smtp.gmail.com
  smtp_port: 587
  username: your-email@gmail.com
  password: your-app-password
  from_name: SALOME Platform

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

security:
  bcrypt_cost: 12
  session_secret: salome-session-secret-2024

features:
  enable_otp: true
  enable_email_verification: true
  enable_payment_gateway: true
  enable_notifications: true

midtrans:
  server_key: "SB-Mid-server-i1dcC7yEZ88t9ojPby0wej3n"
  client_key: "SB-Mid-client-F4GiAgWMbYRqrHzr"
  base_url: "https://api.sandbox.midtrans.com"
  is_production: false

# #STAGING
# midtrans:
#   midtrans_server_key: SB-Mid-server-i1dcC7yEZ88t9ojPby0wej3n
#   midtrans_client_key: SB-Mid-client-F4GiAgWMbYRqrHzr
#   midtrans_base_url: https://api.sandbox.midtrans.com
#   midtrans_default_version: v2
#   midtrans_api_version: v1